#### 卷积

In [1]:
import torch
import torch.nn as nn

data=torch.ones(size=(10,3,28,28))
conv1=nn.Conv2d(in_channels=3,
                    out_channels=6,
                    kernel_size=5,
                    stride=1,
                    padding=0
                )

conv2=nn.Conv2d(6,10,3)
conv3=nn.Conv2d(10,16,5,stride=2,padding=1)
conv4=nn.Conv2d(16,3,5,stride=3,padding=2)

x=conv1(data)
print(x.shape)
x=conv2(x)
print(x.shape)
x=conv3(x)
print(x.shape)
x=conv4(x)
print(x.shape)


torch.Size([10, 6, 24, 24])
torch.Size([10, 10, 22, 22])
torch.Size([10, 16, 10, 10])
torch.Size([10, 3, 4, 4])


#### NiN

In [6]:
import torch
import torch.nn as nn
print(3)
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

class NiN(nn.Module):
    def __init__(self):
        super().__init__()
        self.block1 = nn.Sequential(nn.Conv2d(3,192,5,padding=2),nn.ReLU(inplace=True)
                                    ,nn.Conv2d(192,160,1),nn.ReLU(inplace=True)
                                    ,nn.Conv2d(160,96,1),nn.ReLU(inplace=True)
                                    ,nn.MaxPool2d(kernel_size=3,stride=2)
                                    ,nn.Dropout(0.25))
        self.block2 = nn.Sequential(nn.Conv2d(96,192,5,padding=2),nn.ReLU(inplace=True)
                                    ,nn.Conv2d(192,192,1),nn.ReLU(inplace=True)
                                    ,nn.Conv2d(192,192,1),nn.ReLU(inplace=True)
                                    ,nn.MaxPool2d(kernel_size=3,stride=2)
                                    ,nn.Dropout(0.25))
        self.block3 = nn.Sequential(nn.Conv2d(192,192,3,padding=1),nn.ReLU(inplace=True)
                                    ,nn.Conv2d(192,192,1),nn.ReLU(inplace=True)
                                    ,nn.Conv2d(192,10,1),nn.ReLU(inplace=True)
                                    ,nn.AvgPool2d(7,stride=1)
                                    ,nn.Softmax(dim=1))
    def forward(self,x):
        output = self.block3(self.block2(self.block1(x)))
        return output
data = torch.ones(size=(10,3,32,32))

model=NiN()
model(data).shape

3
cuda


torch.Size([10, 10, 1, 1])

#### cat()函数

In [4]:
import torch
a=torch.randn((2,5))
b=torch.randn((2,3))#-->2,8
c=torch.randn((3,5))#-->5,5
print(a)
print()
print(b) 
print()
print(c)
print()

tensor([[-0.6191,  0.7683, -0.9812,  0.9117, -1.5129],
        [-0.9079,  0.2384, -0.3349, -0.3889,  0.9516]])

tensor([[-0.7978,  0.5805,  0.1777],
        [ 0.2033,  0.5325,  1.5137]])

tensor([[ 1.8078,  0.7524,  1.8993,  1.0485,  0.1140],
        [-0.0696,  0.2065, -1.2179, -1.3237, -0.8022],
        [-1.2036, -0.3425,  0.5374,  0.5788, -0.0843]])



In [14]:
print(torch.cat([a,b],dim=1))#表示在第1维度上拼在一起
print(torch.cat([a,c],dim=0))#表示在第0维度上拼在一起
#总结,哪个维度一样,就按照另一个维度拼接

tensor([[-0.6191,  0.7683, -0.9812,  0.9117, -1.5129, -0.7978,  0.5805,  0.1777],
        [-0.9079,  0.2384, -0.3349, -0.3889,  0.9516,  0.2033,  0.5325,  1.5137]])
tensor([[-0.6191,  0.7683, -0.9812,  0.9117, -1.5129],
        [-0.9079,  0.2384, -0.3349, -0.3889,  0.9516],
        [ 1.8078,  0.7524,  1.8993,  1.0485,  0.1140],
        [-0.0696,  0.2065, -1.2179, -1.3237, -0.8022],
        [-1.2036, -0.3425,  0.5374,  0.5788, -0.0843]])


In [5]:
import torch

a=torch.randn(2,3)
b=torch.randn(1,3)
c=a+b
print(a)
print(b)
print(c)

tensor([[ 1.0295,  0.7706,  0.7189],
        [ 1.7642,  1.0481, -1.2241]])
tensor([[ 0.3924, -0.2087, -0.5352]])
tensor([[ 1.4219,  0.5619,  0.1838],
        [ 2.1566,  0.8394, -1.7592]])


In [ ]:
class Node():
    def __init__(self,val):
        self.val=val

node=Node()
n1=node(1)
print(type(node))
print(type(n1))

SyntaxError: non-default argument follows default argument (1649640625.py, line 1)